# Generated by Django 5.0.4 on 2024-04-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_alter_profile_gender_alter_profile_identity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='identity_type',
            field=models.CharField(blank=True, choices=[('Driver Licence', 'Driver Licence'), ('National Identification Number', 'National Identification Number'), ('International Passport', 'International Passport')], max_length=150, null=True),
        ),
    ]
