"""
Django settings for Hotelsystem project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hw2*1#(0j-0#8kih02*(n5cn9na0#^7#y_tst4ons+0z6vl*qo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # mes app
    'hotel',
    'userauths',
    'addons',
    'user_dashboard',

    # modules python
    'crispy_forms',
    'import_export',
    'mathfilters',
    'ckeditor_uploader',
    'django_ckeditor_5',
    'taggit',
    'anymail',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Hotelsystem.urls'

templates_path = os.path.join(BASE_DIR,'templates')
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [templates_path],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Hotelsystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES ={
   'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'hsm_db',
        'USER': 'postgres',
        'PASSWORD': 'andre',
        'HOST':'localhost',
        'PORT':'5432',
         'OPTIONS': {
            'client_encoding': 'utf-8',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static')
]
MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = "userauths.User"

JAZZMIN_SETTINGS = {
    "site_title": "HMS Admin",
    "site_header": "hms",
    "site_brand": "hms",
    "site_logo": "images/téléchargement.jpeg",
    "welcome_sign": "Welcome to the library",
    "copyright": "Zokou Ltd",

    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Company", "url": "/admin/addons/company/"},
        {"name": "Users", "url": "/admin/userauths/user/"},

        # model admin to link to (Permissions checked against model)
        {"model": "AUTH_USER_MODEL.User"},

       # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "hotel"}, 
    ],

    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": [
        "hotel",
        "hotel.Hotel",
        "hotel.Booking",
        "hotel.Room",
        "hotel.BookingDetail",
        "hotel.Guest",
        "hotel.RoomServices",
        "userauths",
        "addons"],

    "icons": {
        "admin.logEntry":"fas fa-file",

        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        
        "userauths.User":"fas fa-user",
        "userauths.Profile":"fas fa-address-card",

        "hotel.Hotel":"fas fa-th",
        "hotel.Booking":"fas fa-calendar-week",
        "hotel.Room":"fas fa-bed",
        "hotel.BookingDetail":"fas fa-calendar-alt",
        "hotel.Guest":"fas fa-user",
        "hotel.RoomServices":"fas fa-user-cog",
        "hotel.Coupon":"fas fa-tag",
        "hotel.Bookmark":"fas fa-heart",
    },
  
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,

  
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
  
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
   
}


JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "dark_mode_theme":"cyborg",
    "dark_theme":"slate",
    "navbar_small_text":False,
    "footer_small_text":False,
    "body_small_text":True,
    "brand_small_text":False,
    "brand_color":"navbar-indigo",
    "accent":"accent-olive",
    "navbar":"navbar-indigo navbar-dark",
    "no_navbar_border":False,
    "navbar_fixed":False,
    "layout_boxed":False,
    "footer_fixed":False,
    "sidebar_fixed":False,
    "sidebar":"sidebar-dark-indigo",
    "sidebar_nav_small_text":False,
    "sidebar_disable_expand":False,
    "sidebar_nav_child_indent":False,
    "sidebar_nav_compact_style":False,
    "sidebar_nav_legacy_style":False,
    "sidebar_nav_flat_style":False,
    "button_classes":{
        "primary":"btn-primary",
        "secondary":"btn-secondary",
        "info":"btn-info",
        "warning":"btn-warning",
        "danger":"btn-danger",
        "success":"btn-success"
    }
}

customColorPalette = [
      {'color': 'hsl(4, 90%, 58%)','label': 'Red'},
      {'color': 'hsl(340, 82%, 52%)','label': 'Pink'},
      {'color': 'hsl(291, 64%, 42%)','label': 'Purple'},
      {'color': 'hsl(262, 52%, 47%)','label': 'Deep Purple'},
      {'color': 'hsl(231, 48%, 48%)','label': 'Indigo'},
      {'color': 'hsl(207, 90%, 54%)','label': 'Blue' },
  ]



CKEDITOR_5_CONFIGS = {
    'default': {
      'toolbar': [
          'heading', 
          '|', 
          'bold',
          'italic', 
          'link',
          'bulletedList', 
          'numberedList', 
          'blockQuote', 
          'imageUpload', 
        ],

  },
  'extends': {
      'blockToolbar': [
          'paragraph', 'heading1', 'heading2', 'heading3',
          '|',
          'bulletedList', 'numberedList',
          '|',
          'blockQuote',
      ],
      'toolbar': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
      'code','subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
                  'bulletedList', 'numberedList', 'todoList', '|',  'blockQuote', 'imageUpload', '|',
                  'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
                  'insertTable',],
      'image': {
          'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                      'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
          'styles': [
              'full',
              'side',
              'alignLeft',
              'alignRight',
              'alignCenter',
          ]

      },
      'table': {
          'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
          'tableProperties', 'tableCellProperties' ],
          'tableProperties': {
              'borderColors': customColorPalette,
              'backgroundColors': customColorPalette
          },
          'tableCellProperties': {
              'borderColors': customColorPalette,
              'backgroundColors': customColorPalette
          }
      },
      'heading' : {
          'options': [
              { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
              { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
              { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
              { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' }
          ]
      }
  },
  'list': {
      'properties': {
          'styles': 'true',
          'startIndex': 'true',
          'reversed': 'true',
      }
  }
} 
