# Generated by Django 5.0.4 on 2024-04-15 22:19

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_hotel_hid_alter_hotel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=6, max_length=10, prefix='HOTEL', unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('In review', 'In review'), ('Disable', 'Disable'), ('Draft', 'Draft'), ('Rejected', 'Rejected'), ('Live', 'Live')], default='Live', max_length=20),
        ),
    ]
