# Generated by Django 5.0.4 on 2024-04-15 22:22

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_hid_alter_hotel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=10, max_length=15, prefix='HTL', unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('Disable', 'Disable'), ('Draft', 'Draft'), ('Live', 'Live'), ('In review', 'In review'), ('Rejected', 'Rejected')], default='Live', max_length=20),
        ),
    ]
