# Generated by Django 5.0.4 on 2024-04-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_hotel_status_booking_activitylog_hotelfaq_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffonduty',
            options={'verbose_name_plural': 'Staff on duties'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='status_payment',
            field=models.CharField(choices=[('refunded', 'refunded'), ('initiated', 'Initiated'), ('processing', 'Processing'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('expired', 'Expired'), ('refunding', 'Refunding'), ('paid', 'Paid'), ('failed', 'Failed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Rejected', 'Rejected'), ('Live', 'Live'), ('In review', 'In review'), ('Disable', 'Disable')], default='Live', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotelfeatures',
            name='icontype',
            field=models.CharField(blank=True, choices=[('Box icons', 'Box icons'), ('Fontawesome icons', 'Fontawesome icons'), ('Bootstrap icons', 'Bootstrap icons'), ('Flat icons', 'Flat icons'), ('Remi icons', 'Remi icons')], max_length=100, null=True),
        ),
    ]
