# Generated by Django 5.0.4 on 2024-04-16 10:50

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_staffonduty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status_payment',
            field=models.CharField(choices=[('failed', 'Failed'), ('expired', 'Expired'), ('refunded', 'refunded'), ('paid', 'Paid'), ('initiated', 'Initiated'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled'), ('processing', 'Processing'), ('refunding', 'Refunding'), ('pending', 'Pending')], max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('Live', 'Live'), ('Draft', 'Draft'), ('Disable', 'Disable'), ('In review', 'In review'), ('Rejected', 'Rejected')], default='Live', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotelfeatures',
            name='icontype',
            field=models.CharField(blank=True, choices=[('Box icons', 'Box icons'), ('Bootstrap icons', 'Bootstrap icons'), ('Fontawesome icons', 'Fontawesome icons'), ('Flat icons', 'Flat icons'), ('Remi icons', 'Remi icons')], max_length=100, null=True),
        ),
    ]
