# Generated by Django 5.0.4 on 2024-04-16 12:22

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_booking_status_payment_alter_hotel_description_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status_payment',
            field=models.CharField(choices=[('paid', 'Paid'), ('failed', 'Failed'), ('initiated', 'Initiated'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled'), ('refunding', 'Refunding'), ('pending', 'Pending'), ('processing', 'Processing'), ('expired', 'Expired'), ('refunded', 'refunded')], max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('Disable', 'Disable'), ('In review', 'In review'), ('Rejected', 'Rejected'), ('Live', 'Live'), ('Draft', 'Draft')], default='Live', max_length=20),
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='tags',
        ),
        migrations.AlterField(
            model_name='hotelfeatures',
            name='icontype',
            field=models.CharField(blank=True, choices=[('Fontawesome icons', 'Fontawesome icons'), ('Bootstrap icons', 'Bootstrap icons'), ('Box icons', 'Box icons'), ('Remi icons', 'Remi icons'), ('Flat icons', 'Flat icons')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
