# Generated by Django 5.0.4 on 2024-04-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_booking_status_payment_alter_hotel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status_payment',
            field=models.CharField(choices=[('refunding', 'Refunding'), ('expired', 'Expired'), ('initiated', 'Initiated'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'refunded'), ('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('unpaid', 'Unpaid')], max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('Disable', 'Disable'), ('Rejected', 'Rejected'), ('In review', 'In review'), ('Live', 'Live'), ('Draft', 'Draft')], default='Live', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotelfeatures',
            name='icontype',
            field=models.CharField(blank=True, choices=[('Box icons', 'Box icons'), ('Fontawesome icons', 'Fontawesome icons'), ('Bootstrap icons', 'Bootstrap icons'), ('Remi icons', 'Remi icons'), ('Flat icons', 'Flat icons')], max_length=100, null=True),
        ),
    ]
