# Generated by Django 5.0.4 on 2024-04-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_booking_status_payment_alter_hotel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status_payment',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('refunded', 'refunded'), ('failed', 'Failed'), ('refunding', 'Refunding'), ('cancelled', 'Cancelled'), ('processing', 'Processing'), ('paid', 'Paid'), ('pending', 'Pending'), ('unpaid', 'Unpaid'), ('expired', 'Expired')], max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('In review', 'In review'), ('Disable', 'Disable'), ('Live', 'Live'), ('Rejected', 'Rejected'), ('Draft', 'Draft')], default='Live', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotelfeatures',
            name='icontype',
            field=models.CharField(blank=True, choices=[('Bootstrap icons', 'Bootstrap icons'), ('Box icons', 'Box icons'), ('Flat icons', 'Flat icons'), ('Remi icons', 'Remi icons'), ('Fontawesome icons', 'Fontawesome icons')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
