# Generated by Django 5.0.4 on 2024-04-17 12:26

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_alter_booking_status_payment_alter_hotel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status_payment',
            field=models.CharField(choices=[('pending', 'Pending'), ('refunding', 'Refunding'), ('processing', 'Processing'), ('unpaid', 'Unpaid'), ('expired', 'Expired'), ('initiated', 'Initiated'), ('paid', 'Paid'), ('refunded', 'refunded'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('In review', 'In review'), ('Rejected', 'Rejected'), ('Disable', 'Disable'), ('Live', 'Live')], default='Live', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotelfeatures',
            name='icontype',
            field=models.CharField(blank=True, choices=[('Remi icons', 'Remi icons'), ('Fontawesome icons', 'Fontawesome icons'), ('Bootstrap icons', 'Bootstrap icons'), ('Flat icons', 'Flat icons'), ('Box icons', 'Box icons')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='rid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=6, max_length=10, prefix='ROOM', unique=True),
        ),
    ]
